package com.rabitah.frontend.controller;

import com.fasterxml.jackson.databind.JsonNode;import com.rabitah.frontend.AppContext;import java.io.File;import java.time.Year;import java.util.*;import javafx.animation.KeyFrame;import javafx.animation.Timeline;import javafx.application.Platform;import javafx.fxml.FXML;import javafx.scene.control.*;import javafx.stage.FileChooser;import javafx.util.Duration;

public final class ShellController {
 private final AppContext context;private final Map<String,String> postIds=new LinkedHashMap<>(),commentIds=new LinkedHashMap<>(),commentAuthors=new LinkedHashMap<>(),paperIds=new LinkedHashMap<>(),paperFiles=new LinkedHashMap<>(),users=new LinkedHashMap<>(),courses=new LinkedHashMap<>(),pendingUsers=new LinkedHashMap<>(),pendingPosts=new LinkedHashMap<>(),pendingPapers=new LinkedHashMap<>();private String conversationId,communityId,replyParentId;private Timeline approvalPolling;private AutoCloseable realtimeSubscription;
 @FXML private Label welcome,feedStatus,chatWith,communityName,profileDetails,replyTarget,paperStatus,approvalSummary,serverLabel;@FXML private TextArea postText,noticeBody;@FXML private TextField commentText,noticeTitle,paperTitle,examYear,paperSearch,messageText,decisionReason;@FXML private ListView<String> feedList,commentList,noticeList,paperList,messageList,communityList,userApprovalList,postApprovalList,paperApprovalList;@FXML private ComboBox<String> noticeType,courseBox,chatUserBox;@FXML private Button publishNoticeButton,uploadPaperButton;@FXML private Tab approvalsTab;
 public ShellController(AppContext context){this.context=context;}
 @FXML private void initialize(){var u=context.session().current().user();String identity=u.studentId()==null?u.loginId():u.studentId();welcome.setText("Welcome, "+u.nickname()+" ("+identity+")");serverLabel.setText("Server: "+context.apiBase().getHost()+":"+context.apiBase().getPort());profileDetails.setText("Nickname: "+u.nickname()+"\nLogin ID: "+u.loginId()+"\nStudent ID: "+value(u.studentId())+"\nRole: "+u.role().replace('_',' ')+"\nDepartment: "+value(u.department())+"\nSection: "+value(u.section())+"\nAcademic year: "+value(u.academicYear()));noticeType.getItems().setAll("GENERAL","ACADEMIC","EXAM","EVENT","EMERGENCY");noticeType.setValue("GENERAL");boolean admin=u.role().equals("SYSTEM_ADMIN");publishNoticeButton.setDisable(!admin);uploadPaperButton.setDisable(false);approvalsTab.setDisable(!admin);feedList.getSelectionModel().selectedItemProperty().addListener((observable,oldValue,newValue)->{cancelReply();refreshComments();});refreshFeed();refreshNotices();refreshPapers();loadUsers();if(admin){refreshApprovals();realtimeSubscription=context.approvals().subscribe(()->Platform.runLater(this::refreshApprovals));approvalPolling=new Timeline(new KeyFrame(Duration.seconds(10),event->refreshApprovals()));approvalPolling.setCycleCount(Timeline.INDEFINITE);approvalPolling.play();}if(u.department()!=null)refreshCommunity();else communityName.setText("Community oversight requires a scoped account");}
 @FXML private void refreshFeed(){run(context.api().getJson("posts/feed"),json->{feedList.getItems().clear();postIds.clear();for(JsonNode p:json){String line=p.path("authorNickname").asText()+" ["+p.path("authorStudentId").asText("SYSTEM")+"]\n"+p.path("body").asText()+"\n👍 "+p.path("likes").asInt()+"   👎 "+p.path("dislikes").asInt()+"   💬 "+p.path("comments").asInt();feedList.getItems().add(line);postIds.put(line,p.path("id").asText());}feedStatus.setText(feedList.getItems().size()+" posts");});}
 @FXML private void createPost(){if(postText.getText().isBlank())return;var u=context.session().current().user();Map<String,Object> request=new LinkedHashMap<>();request.put("body",postText.getText());request.put("department",u.department());request.put("section",u.section());request.put("academicYear",u.academicYear());run(context.api().postJson("posts",request),x->{postText.clear();if("PENDING".equals(x.path("status").asText()))feedStatus.setText("Post submitted. It will appear after SysAdmin approval.");else{feedStatus.setText("Post published.");refreshFeed();}});}
 @FXML private void likePost(){react("LIKE");}@FXML private void dislikePost(){react("DISLIKE");}private void react(String type){String id=selected(postIds,feedList);if(id!=null)run(context.api().putJson("posts/"+id+"/reaction",Map.of("type",type)),x->refreshFeed());}
 @FXML private void commentPost(){String id=selected(postIds,feedList);if(id!=null&&!commentText.getText().isBlank()){Map<String,Object> request=new LinkedHashMap<>();request.put("body",commentText.getText());request.put("parentCommentId",replyParentId);run(context.api().postJson("posts/"+id+"/comments",request),x->{commentText.clear();cancelReply();refreshComments();refreshFeedKeeping(id);});}}
 @FXML private void refreshComments(){String postId=selected(postIds,feedList);commentList.getItems().clear();commentIds.clear();commentAuthors.clear();if(postId==null){replyTarget.setText("Select a post to see comments");return;}replyTarget.setText("Comments on selected post");run(context.api().getJson("posts/"+postId+"/comments"),json->{Map<String,JsonNode> comments=new LinkedHashMap<>();for(JsonNode c:json)comments.put(c.path("id").asText(),c);for(JsonNode c:json){String parent=c.path("parentCommentId").isNull()?null:c.path("parentCommentId").asText(null);String prefix=parent==null?"":"    ↳ ";String line=prefix+c.path("authorNickname").asText()+" ["+c.path("authorStudentId").asText("SYSTEM")+"]\n"+prefix+c.path("body").asText()+"\n"+prefix+"👍 "+c.path("likes").asInt()+"   👎 "+c.path("dislikes").asInt();commentList.getItems().add(line);commentIds.put(line,c.path("id").asText());commentAuthors.put(line,c.path("authorNickname").asText());}if(json.isEmpty())replyTarget.setText("No comments yet — start the discussion");});}
 @FXML private void likeComment(){reactToComment("LIKE");}@FXML private void dislikeComment(){reactToComment("DISLIKE");}private void reactToComment(String type){String id=selected(commentIds,commentList);if(id!=null)run(context.api().putJson("comments/"+id+"/reaction",Map.of("type",type)),x->refreshComments());}
 @FXML private void replyToComment(){String line=commentList.getSelectionModel().getSelectedItem();String id=commentIds.get(line);if(id!=null){replyParentId=id;replyTarget.setText("Replying to "+commentAuthors.get(line));commentText.requestFocus();}}
 @FXML private void cancelReply(){replyParentId=null;if(replyTarget!=null&&selected(postIds,feedList)!=null)replyTarget.setText("Comments on selected post");}
 private void refreshFeedKeeping(String postId){run(context.api().getJson("posts/feed"),json->{feedList.getItems().clear();postIds.clear();String select=null;for(JsonNode p:json){String line=p.path("authorNickname").asText()+" ["+p.path("authorStudentId").asText("SYSTEM")+"]\n"+p.path("body").asText()+"\n👍 "+p.path("likes").asInt()+"   👎 "+p.path("dislikes").asInt()+"   💬 "+p.path("comments").asInt();feedList.getItems().add(line);postIds.put(line,p.path("id").asText());if(postId.equals(p.path("id").asText()))select=line;}if(select!=null)feedList.getSelectionModel().select(select);feedStatus.setText(feedList.getItems().size()+" posts");});}
 @FXML private void refreshNotices(){run(context.api().getJson("notices"),json->{noticeList.getItems().clear();for(JsonNode n:json)noticeList.getItems().add(n.path("type").asText()+" — "+n.path("title").asText()+"\n"+n.path("body").asText()+"\nAudience: "+n.path("department").asText("All departments"));});}
 @FXML private void publishNotice(){if(noticeTitle.getText().isBlank()||noticeBody.getText().isBlank())return;run(context.api().postJson("notices",Map.of("title",noticeTitle.getText(),"body",noticeBody.getText(),"type",noticeType.getValue())),x->{noticeTitle.clear();noticeBody.clear();refreshNotices();});}
 @FXML private void refreshPapers(){run(context.api().getJson("question-papers?q="+java.net.URLEncoder.encode(paperSearch.getText(),java.nio.charset.StandardCharsets.UTF_8)),json->{paperList.getItems().clear();paperIds.clear();paperFiles.clear();for(JsonNode p:json){String line=p.path("department").asText()+" / "+p.path("courseCode").asText()+" — "+p.path("title").asText()+" ("+p.path("examYear").asInt()+")\nPDF: "+p.path("filename").asText();paperList.getItems().add(line);paperIds.put(line,p.path("id").asText());paperFiles.put(line,safeFilename(p.path("filename").asText("question.pdf")));}paperStatus.setText(json.size()+" PDF file(s) available. Select one and click Download PDF.");});loadCourses();}
 private void loadCourses(){run(context.api().getJson("question-papers/courses"),json->{courses.clear();courseBox.getItems().clear();for(JsonNode c:json){String label=c.path("code").asText()+" — "+c.path("name").asText();courses.put(label,c.path("id").asText());courseBox.getItems().add(label);}});}
 @FXML private void uploadPaper(){if(courseBox.getValue()==null||paperTitle.getText().isBlank())return;FileChooser chooser=new FileChooser();chooser.setTitle("Choose question paper PDF");chooser.getExtensionFilters().add(new FileChooser.ExtensionFilter("PDF files","*.pdf"));File file=chooser.showOpenDialog(courseBox.getScene().getWindow());if(file==null)return;String year=examYear.getText().isBlank()?String.valueOf(Year.now().getValue()):examYear.getText();run(context.api().uploadPdf("question-papers",Map.of("courseId",courses.get(courseBox.getValue()),"title",paperTitle.getText(),"examYear",year),file.toPath()),x->{paperTitle.clear();if("PENDING".equals(x.path("status").asText()))paperStatus.setText("PDF submitted. It will be listed after SysAdmin approval.");else{paperStatus.setText("PDF uploaded and published.");refreshPapers();}});}
 @FXML private void downloadPaper(){String line=paperList.getSelectionModel().getSelectedItem();String id=paperIds.get(line);if(id==null){paperStatus.setText("Please select a question paper first.");return;}FileChooser chooser=new FileChooser();chooser.setTitle("Save question paper PDF");chooser.setInitialFileName(paperFiles.get(line));chooser.getExtensionFilters().add(new FileChooser.ExtensionFilter("PDF files","*.pdf"));File target=chooser.showSaveDialog(paperList.getScene().getWindow());if(target==null)return;run(context.api().download("question-papers/"+id+"/download",target.toPath()),path->paperStatus.setText("Downloaded to "+path.toAbsolutePath()));}
 private String safeFilename(String name){String clean=name.replaceAll("[\\\\/:*?\"<>|\\r\\n]","_");if(!clean.toLowerCase(Locale.ROOT).endsWith(".pdf"))clean+=".pdf";return clean.isBlank()?"question.pdf":clean;}
 private void loadUsers(){run(context.api().getJson("chat/users"),json->{users.clear();chatUserBox.getItems().clear();for(JsonNode u:json){String label=u.path("nickname").asText()+" ("+u.path("loginId").asText()+")";users.put(label,u.path("loginId").asText());chatUserBox.getItems().add(label);}});}
 @FXML private void openConversation(){if(chatUserBox.getValue()==null)return;run(context.api().postJson("chat/conversations/with/"+users.get(chatUserBox.getValue()),Map.of()),json->{conversationId=json.path("id").asText();chatWith.setText("Chat with "+json.path("otherNickname").asText());refreshMessages();});}
 private void refreshMessages(){if(conversationId==null)return;run(context.api().getJson("chat/conversations/"+conversationId+"/messages"),json->{messageList.getItems().clear();for(JsonNode m:json)messageList.getItems().add(m.path("senderNickname").asText()+": "+m.path("body").asText());});}
 @FXML private void sendMessage(){if(conversationId==null||messageText.getText().isBlank())return;run(context.api().postJson("chat/conversations/"+conversationId+"/messages",Map.of("body",messageText.getText())),x->{messageText.clear();refreshMessages();});}
 @FXML private void refreshCommunity(){run(context.api().getJson("community/rooms/mine"),room->{communityId=room.path("id").asText();communityName.setText(room.path("name").asText());run(context.api().getJson("community/rooms/"+communityId+"/messages"),json->{communityList.getItems().clear();for(JsonNode m:json)communityList.getItems().add(m.path("authorNickname").asText()+"\n"+m.path("body").asText());});});}
 @FXML private void refreshApprovals(){refreshApprovalSummary();loadApprovals("users",userApprovalList,pendingUsers,n->n.path("studentId").asText()+" — "+n.path("legalName").asText()+"\n"+n.path("department").asText()+" Year "+n.path("academicYear").asInt()+" Section "+n.path("section").asText());loadApprovals("posts",postApprovalList,pendingPosts,n->n.path("authorNickname").asText()+" ["+n.path("authorStudentId").asText()+"]\n"+n.path("body").asText());loadApprovals("papers",paperApprovalList,pendingPapers,n->n.path("authorNickname").asText()+" ["+n.path("authorStudentId").asText()+"]\n"+n.path("courseCode").asText()+" — "+n.path("title").asText()+" ("+n.path("filename").asText()+")");}
 private void refreshApprovalSummary(){runApproval(context.api().getJson("admin/approvals/summary"),s->{long total=s.path("users").asLong()+s.path("posts").asLong()+s.path("papers").asLong();approvalSummary.setText((total>0?"🔔 ":"")+s.path("users").asInt()+" students • "+s.path("posts").asInt()+" posts • "+s.path("papers").asInt()+" PDFs pending");});}
 private void loadApprovals(String kind,ListView<String> list,Map<String,String> ids,java.util.function.Function<JsonNode,String> format){String selectedId=selected(ids,list);runApproval(context.api().getJson("admin/approvals/"+kind),json->{list.getItems().clear();ids.clear();String restore=null;for(JsonNode n:json){String line=format.apply(n);list.getItems().add(line);ids.put(line,n.path("id").asText());if(n.path("id").asText().equals(selectedId))restore=line;}if(restore!=null)list.getSelectionModel().select(restore);});}
 @FXML private void approveUser(){decide("users",pendingUsers,userApprovalList,"APPROVE");}@FXML private void rejectUser(){decide("users",pendingUsers,userApprovalList,"REJECT");}@FXML private void approvePost(){decide("posts",pendingPosts,postApprovalList,"APPROVE");}@FXML private void rejectPost(){decide("posts",pendingPosts,postApprovalList,"REJECT");}@FXML private void approvePaper(){decide("papers",pendingPapers,paperApprovalList,"APPROVE");}@FXML private void rejectPaper(){decide("papers",pendingPapers,paperApprovalList,"REJECT");}
 private void decide(String kind,Map<String,String> ids,ListView<String> list,String action){String id=selected(ids,list);if(id==null){approvalSummary.setText("Select a request first.");return;}approvalSummary.setText("Saving decision...");Map<String,Object> request=new LinkedHashMap<>();request.put("action",action);request.put("reason",decisionReason.getText().isBlank()?null:decisionReason.getText());runApproval(context.api().putJson("admin/approvals/"+kind+"/"+id,request),x->{decisionReason.clear();approvalSummary.setText(x.path("message").asText("Decision saved"));refreshApprovals();if(kind.equals("posts"))refreshFeed();if(kind.equals("papers"))refreshPapers();});}
 @FXML private void logout(){if(approvalPolling!=null)approvalPolling.stop();try{if(realtimeSubscription!=null)realtimeSubscription.close();}catch(Exception ignored){}context.session().clear();context.router().showLogin();}
 private <T> void run(java.util.concurrent.CompletableFuture<T> task,java.util.function.Consumer<T> success){task.whenComplete((v,e)->Platform.runLater(()->{if(e!=null){Throwable c=e.getCause()==null?e:e.getCause();feedStatus.setText("Error: "+c.getMessage());feedStatus.setStyle("-fx-text-fill:#b42318");}else{feedStatus.setStyle("");success.accept(v);}}));}
 private <T> void runApproval(java.util.concurrent.CompletableFuture<T> task,java.util.function.Consumer<T> success){task.whenComplete((v,e)->Platform.runLater(()->{if(e!=null){Throwable c=e.getCause()==null?e:e.getCause();approvalSummary.setText("Approval error: "+c.getMessage());approvalSummary.setStyle("-fx-text-fill:#b42318");}else{approvalSummary.setStyle("");success.accept(v);}}));}
 private String selected(Map<String,String> map,ListView<String> list){return map.get(list.getSelectionModel().getSelectedItem());}private String value(Object v){return v==null?"Not applicable":v.toString();}private String valueOrEmpty(Object v){return v==null?"":v.toString();}
}
