package com.rabitah.backend.chat;

import com.rabitah.backend.common.ApiException; import com.rabitah.backend.security.CurrentUserService; import com.rabitah.backend.user.User;
import jakarta.validation.Valid; import jakarta.validation.constraints.*; import java.time.Instant; import java.util.*;
import org.springframework.http.HttpStatus; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.security.core.Authentication; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/api/v1/chat") public class ChatController {
 private final JdbcTemplate jdbc;private final CurrentUserService current;public ChatController(JdbcTemplate jdbc,CurrentUserService current){this.jdbc=jdbc;this.current=current;}
 @GetMapping("/users") public List<ChatUser> users(Authentication auth){User me=current.require(auth);return jdbc.query("select id,coalesce(student_id,login_id),nickname,department_code from users where status='ACTIVE' and id<>? order by nickname",(rs,n)->new ChatUser(rs.getObject(1,UUID.class),rs.getString(2),rs.getString(3),rs.getString(4)),me.getId());}
 @GetMapping("/conversations") public List<Conversation> conversations(Authentication auth){User me=current.require(auth);return jdbc.query("select c.id,coalesce(u.student_id,u.login_id),u.nickname,max(m.sent_at) last_at from private_conversations c join users u on u.id=case when c.participant_one=? then c.participant_two else c.participant_one end left join private_messages m on m.conversation_id=c.id where c.participant_one=? or c.participant_two=? group by c.id,u.student_id,u.login_id,u.nickname order by last_at desc nulls last",(rs,n)->new Conversation(rs.getObject(1,UUID.class),rs.getString(2),rs.getString(3),rs.getObject(4,java.time.OffsetDateTime.class)==null?null:rs.getObject(4,java.time.OffsetDateTime.class).toInstant()),me.getId(),me.getId(),me.getId());}
 @PostMapping("/conversations/with/{loginId}") @Transactional public Conversation open(@PathVariable String loginId,Authentication auth){User me=current.require(auth);Map<String,Object> other=find(loginId);UUID oid=(UUID)other.get("id");if(oid.equals(me.getId()))throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_RECIPIENT","Choose another user");jdbc.update("insert into private_conversations(id,participant_one,participant_two) select gen_random_uuid(),?,? where not exists(select 1 from private_conversations where (participant_one=? and participant_two=?) or (participant_one=? and participant_two=?))",me.getId(),oid,me.getId(),oid,oid,me.getId());return conversations(auth).stream().filter(c->c.otherLoginId().equalsIgnoreCase(loginId)).findFirst().orElseThrow();}
 @GetMapping("/conversations/{id}/messages") public List<Message> messages(@PathVariable UUID id,Authentication auth){User me=current.require(auth);member(id,me);return jdbc.query("select m.id,m.body,m.sent_at,coalesce(u.student_id,u.login_id),u.nickname from private_messages m join users u on u.id=m.sender_id where conversation_id=? order by sent_at",(rs,n)->new Message(rs.getObject(1,UUID.class),rs.getString(2),rs.getObject(3,java.time.OffsetDateTime.class).toInstant(),rs.getString(4),rs.getString(5)),id);}
 @PostMapping("/conversations/{id}/messages") @ResponseStatus(HttpStatus.CREATED) @Transactional public Message send(@PathVariable UUID id,@Valid @RequestBody SendRequest r,Authentication auth){User me=current.require(auth);member(id,me);UUID mid=UUID.randomUUID();jdbc.update("insert into private_messages(id,conversation_id,sender_id,client_message_id,body) values(?,?,?,?,?)",mid,id,me.getId(),UUID.randomUUID(),r.body().trim());return messages(id,auth).stream().filter(m->m.id().equals(mid)).findFirst().orElseThrow();}
 private void member(UUID id,User u){Long n=jdbc.queryForObject("select count(*) from private_conversations where id=? and (participant_one=? or participant_two=?)",Long.class,id,u.getId(),u.getId());if(n==0)throw new ApiException(HttpStatus.NOT_FOUND,"CONVERSATION_NOT_FOUND","Conversation not found");}
 private Map<String,Object> find(String id){List<Map<String,Object>> r=jdbc.queryForList("select id from users where status='ACTIVE' and (lower(student_id)=lower(?) or lower(login_id)=lower(?))",id,id);if(r.isEmpty())throw new ApiException(HttpStatus.NOT_FOUND,"USER_NOT_FOUND","User not found");return r.getFirst();}
 public record SendRequest(@NotBlank @Size(max=2000)String body){} public record ChatUser(UUID id,String loginId,String nickname,String department){} public record Conversation(UUID id,String otherLoginId,String otherNickname,Instant lastMessageAt){} public record Message(UUID id,String body,Instant sentAt,String senderLoginId,String senderNickname){}
}
