package com.rabitah.backend.auth;
import com.rabitah.backend.academic.*; import com.rabitah.backend.auth.dto.*; import com.rabitah.backend.common.ApiException; import com.rabitah.backend.user.*;
import org.springframework.beans.factory.annotation.Value; import org.springframework.http.HttpStatus; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.security.oauth2.jose.jws.SignatureAlgorithm; import org.springframework.security.oauth2.jwt.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service public class AuthService {
 private final UserRepository users; private final StudentRosterRepository roster; private final PasswordEncoder passwords; private final JwtEncoder encoder; private final long minutes;
 public AuthService(UserRepository users,StudentRosterRepository roster,PasswordEncoder passwords,JwtEncoder encoder,@Value("${rabitah.security.access-minutes:30}") long minutes){this.users=users;this.roster=roster;this.passwords=passwords;this.encoder=encoder;this.minutes=minutes;}
 @Transactional public String register(RegisterRequest r){if(users.existsByStudentIdIgnoreCase(r.studentId()))throw new ApiException(HttpStatus.CONFLICT,"ACCOUNT_EXISTS","An account already exists for this student ID");StudentRoster row=roster.findByStudentIdIgnoreCase(r.studentId()).orElseThrow(()->new ApiException(HttpStatus.BAD_REQUEST,"ROSTER_MISMATCH","Registration details do not match the active roster"));if(!row.matches(r.legalName(),r.department(),r.section(),r.currentYear()))throw new ApiException(HttpStatus.BAD_REQUEST,"ROSTER_MISMATCH","Registration details do not match the active roster");if(r.verificationCode()!=null&&!r.verificationCode().isBlank())throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_VERIFICATION_CODE","The verification code is invalid or unavailable");users.save(new User(row.getStudentId(),row.getStudentId(),row.getLegalName(),r.nickname(),passwords.encode(r.password()),Role.STUDENT,AccountStatus.PENDING,row.getDepartmentCode(),row.getSectionCode(),row.getCurrentYear()));return "Registration submitted for moderator approval";}
 @Transactional(readOnly=true) public AuthResponse login(LoginRequest r){User u=users.findByLoginIdIgnoreCase(r.loginId()).orElseThrow(this::badLogin);if(u.getStatus()!=AccountStatus.ACTIVE||!passwords.matches(r.password(),u.getPasswordHash()))throw badLogin();Instant now=Instant.now(),exp=now.plus(Duration.ofMinutes(minutes));JwtClaimsSet.Builder b=JwtClaimsSet.builder().issuer("rabitah-api").issuedAt(now).expiresAt(exp).subject(u.getId().toString()).claim("loginId",u.getLoginId()).claim("role",u.getRole().name()).claim("tokenVersion",u.getTokenVersion());if(u.getDepartmentCode()!=null)b.claim("department",u.getDepartmentCode());if(u.getSectionCode()!=null)b.claim("section",u.getSectionCode());String access=encoder.encode(JwtEncoderParameters.from(JwsHeader.with(SignatureAlgorithm.HS256).build(),b.build())).getTokenValue();return new AuthResponse(access,null,Duration.between(now,exp).toSeconds(),new AuthResponse.UserSummary(u.getId(),u.getLoginId(),u.getStudentId(),u.getNickname(),u.getRole().name(),u.getDepartmentCode(),u.getSectionCode(),u.getAcademicYear()));}
 private ApiException badLogin(){return new ApiException(HttpStatus.UNAUTHORIZED,"INVALID_CREDENTIALS","Invalid credentials or inactive account");}
}
