package com.rabitah.backend.question;

import com.rabitah.backend.common.ApiException; import com.rabitah.backend.security.CurrentUserService; import com.rabitah.backend.user.*;
import java.io.*; import java.nio.file.*; import java.time.Instant; import java.util.*;
import org.springframework.beans.factory.annotation.Value; import org.springframework.core.io.*; import org.springframework.http.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.security.core.Authentication; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile;

@RestController @RequestMapping("/api/v1/question-papers") public class QuestionPaperController {
 private final JdbcTemplate jdbc;private final CurrentUserService current;private final Path root;
 public QuestionPaperController(JdbcTemplate jdbc,CurrentUserService current,@Value("${rabitah.storage.local-root}") String root)throws IOException{this.jdbc=jdbc;this.current=current;this.root=Paths.get(root).toAbsolutePath().normalize();Files.createDirectories(this.root);}
 @GetMapping public List<PaperView> list(@RequestParam(defaultValue="")String q,Authentication auth){current.require(auth);String like="%"+q.toLowerCase()+"%";return jdbc.query("select qp.id,qp.title,qp.description,qp.exam_year,qp.semester,qp.original_name,qp.created_at,c.course_code,c.course_name,c.department_code,qp.status from question_papers qp join courses c on c.id=qp.course_id where qp.status='APPROVED' and (lower(qp.title) like ? or lower(c.course_code) like ? or lower(c.course_name) like ?) order by c.department_code, c.course_code, qp.exam_year desc, qp.semester, lower(qp.title), qp.created_at desc",this::paper,like,like,like);}
 @GetMapping("/courses") public List<CourseView> courses(Authentication auth){current.require(auth);return jdbc.query("select id,course_code,course_name,department_code,academic_year,semester from courses where active order by department_code,academic_year,course_code",(rs,n)->new CourseView(rs.getObject(1,UUID.class),rs.getString(2),rs.getString(3),rs.getString(4),rs.getInt(5),rs.getInt(6)));}
 @PostMapping(consumes=MediaType.MULTIPART_FORM_DATA_VALUE) @ResponseStatus(HttpStatus.CREATED) @Transactional public PaperView upload(@RequestParam UUID courseId,@RequestParam String title,@RequestParam(required=false)String description,@RequestParam int examYear,@RequestPart MultipartFile file,Authentication auth)throws IOException{User u=current.require(auth);if(file.isEmpty()||!"application/pdf".equalsIgnoreCase(file.getContentType())||file.getOriginalFilename()==null||!file.getOriginalFilename().toLowerCase().endsWith(".pdf"))throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_FILE","A non-empty PDF file is required");UUID id=UUID.randomUUID();String key="questions/"+id+".pdf";Path target=root.resolve(key);Files.createDirectories(target.getParent());file.transferTo(target);String status=u.getRole()==Role.SYSTEM_ADMIN?"APPROVED":"PENDING";try{Map<String,Object> c=jdbc.queryForMap("select academic_year,semester from courses where id=?",courseId);jdbc.update("insert into question_papers(id,course_id,academic_year,semester,exam_year,title,description,storage_key,original_name,content_type,size_bytes,uploaded_by,status) values(?,?,?,?,?,?,?,?,?,?,?,?,?)",id,courseId,c.get("academic_year"),c.get("semester"),examYear,title.trim(),description,key,safe(file.getOriginalFilename()),"application/pdf",file.getSize(),u.getId(),status);}catch(RuntimeException e){Files.deleteIfExists(target);throw e;}return jdbc.queryForObject("select qp.id,qp.title,qp.description,qp.exam_year,qp.semester,qp.original_name,qp.created_at,c.course_code,c.course_name,c.department_code,qp.status from question_papers qp join courses c on c.id=qp.course_id where qp.id=?",this::paper,id);}
 @GetMapping("/{id}/download") public ResponseEntity<Resource> download(@PathVariable UUID id,Authentication auth)throws IOException{User u=current.require(auth);List<Map<String,Object>> rows=jdbc.queryForList("select storage_key,original_name,status,uploaded_by from question_papers where id=?",id);if(rows.isEmpty())throw new ApiException(HttpStatus.NOT_FOUND,"PAPER_NOT_FOUND","Question paper not found");Map<String,Object> paper=rows.getFirst();if(!"APPROVED".equals(paper.get("status"))&&u.getRole()!=Role.SYSTEM_ADMIN&&!u.getId().equals(paper.get("uploaded_by")))throw new ApiException(HttpStatus.FORBIDDEN,"PAPER_PENDING","This paper is waiting for approval");Path path=root.resolve((String)paper.get("storage_key")).normalize();if(!path.startsWith(root)||!Files.exists(path))throw new ApiException(HttpStatus.NOT_FOUND,"FILE_NOT_FOUND","Question paper file not found");return ResponseEntity.ok().contentType(MediaType.APPLICATION_PDF).header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=\""+safe((String)paper.get("original_name"))+"\"").body(new FileSystemResource(path));}
 private PaperView paper(java.sql.ResultSet rs,int n)throws java.sql.SQLException{return new PaperView(rs.getObject(1,UUID.class),rs.getString(2),rs.getString(3),rs.getInt(4),rs.getInt(5),rs.getString(6),rs.getObject(7,java.time.OffsetDateTime.class).toInstant(),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11));}
 private String safe(String n){return n==null?"question.pdf":n.replaceAll("[\\r\\n\\\"]","_");}
 public record PaperView(UUID id,String title,String description,int examYear,int semester,String filename,Instant createdAt,String courseCode,String courseName,String department,String status){}
 public record CourseView(UUID id,String code,String name,String department,int academicYear,int semester){}
}
