package com.rabitah.backend.community;

import com.rabitah.backend.common.ApiException;import com.rabitah.backend.security.CurrentUserService;import com.rabitah.backend.user.*;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.time.Instant;import java.util.*;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.core.Authentication;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/api/v1/community") public class CommunityController {
 private final JdbcTemplate jdbc;private final CurrentUserService current;public CommunityController(JdbcTemplate jdbc,CurrentUserService current){this.jdbc=jdbc;this.current=current;}
 @GetMapping("/rooms/mine") public Room mine(Authentication auth){User u=current.require(auth);if(u.getDepartmentCode()==null)throw new ApiException(HttpStatus.BAD_REQUEST,"NO_COMMUNITY","This account has no student community");return jdbc.queryForObject("select id,name,department_code,section_code,academic_year from community_rooms where department_code=? and section_code=? and academic_year=?",(rs,n)->new Room(rs.getObject(1,UUID.class),rs.getString(2),rs.getString(3),rs.getString(4),rs.getInt(5)),u.getDepartmentCode(),u.getSectionCode(),u.getAcademicYear());}
 @GetMapping("/rooms/{id}/messages") public List<Message> messages(@PathVariable UUID id,Authentication auth){User u=current.require(auth);access(id,u);return jdbc.query("select m.id,m.body,m.created_at,u.nickname,coalesce(u.student_id,u.login_id) from community_messages m join users u on u.id=m.author_id where room_id=? order by m.created_at",(rs,n)->new Message(rs.getObject(1,UUID.class),rs.getString(2),rs.getObject(3,java.time.OffsetDateTime.class).toInstant(),rs.getString(4),rs.getString(5)),id);}
 @PostMapping("/rooms/{id}/messages") @ResponseStatus(HttpStatus.CREATED) @Transactional public Message publish(@PathVariable UUID id,@Valid @RequestBody MessageRequest r,Authentication auth){User u=current.require(auth);if(u.getRole()!=Role.MODERATOR&&u.getRole()!=Role.SYSTEM_ADMIN)throw new ApiException(HttpStatus.FORBIDDEN,"FORBIDDEN","Only moderators may publish community announcements");if(u.getRole()==Role.MODERATOR)access(id,u);UUID mid=UUID.randomUUID();jdbc.update("insert into community_messages(id,room_id,author_id,body) values(?,?,?,?)",mid,id,u.getId(),r.body().trim());return jdbc.queryForObject("select m.id,m.body,m.created_at,u.nickname,coalesce(u.student_id,u.login_id) from community_messages m join users u on u.id=m.author_id where m.id=?",(rs,n)->new Message(rs.getObject(1,UUID.class),rs.getString(2),rs.getObject(3,java.time.OffsetDateTime.class).toInstant(),rs.getString(4),rs.getString(5)),mid);}
 private void access(UUID id,User u){Long n=jdbc.queryForObject("select count(*) from community_rooms where id=? and (?='SYSTEM_ADMIN' or department_code=? and section_code=? and academic_year=?)",Long.class,id,u.getRole().name(),u.getDepartmentCode(),u.getSectionCode(),u.getAcademicYear());if(n==0)throw new ApiException(HttpStatus.FORBIDDEN,"COMMUNITY_FORBIDDEN","This room is outside your community");}
 public record MessageRequest(@NotBlank @Size(max=3000)String body){} public record Room(UUID id,String name,String department,String section,int academicYear){} public record Message(UUID id,String body,Instant createdAt,String authorNickname,String authorLoginId){}
}
